# Generated by Django 4.1.5 on 2023-12-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tunits',
            options={'managed': True},
        ),
    ]
